oVirt/ovirt-engine-ui-extensions

- .github/workflows/comment-to-trigger-ost.yaml
Add a workflow triggered by adding a comment "/ost" to a PR that will start an OST run against the PR.
The workflow can only be trigger by users whose association to the repository is one of:
- COLLABORATOR (i.e. Maintainer) of the repository
- MEMBER of the organization that owns the repository (oVirt)
> Add OST trigger

- package.json
- packaging/spec.in
- zanata/zanata.xml
To keep translations and ansible dependencies between ovirt 4.4 (project version 1.2) and ovirt 4.5 separate, bump the project version to 1.3.
Update the project dependencies based on a ovirt 4.5 target.
The zanata project version has been updated accordingly:
- Translations for ovirt 4.4 / project 1.2 are at: https://zanata.ovirt.org/iteration/view/ovirt-engine-ui-extensions/1.2
- Translations for ovirt 4.5 / project 1.3 are at: https://zanata.ovirt.org/iteration/view/ovirt-engine-ui-extensions/1.3
> Bump version to 1.3.0 for ovirt 4.5

- src/dashboard/Dashboard.js
- src/dashboard/MonitoringPortalLink.js
- src/dashboard/dataShapes.js
- src/intl/messages.js
- static/css/dashboard.css
If the URL for the engine's grafana instance is available from the `dashboard_data` fetch, render the link in the upper right
hand side of the dashboard.  This allows the user to click directly to the monitoring portal without jumping back to the welcome page first.
If no URL is provided from the `dashboard_data`fetch, no link is rendered.
Bug-Url: https://bugzilla.redhat.com/show_bug.cgi?id=1991482
Require ovirt-engine PR: https://github.com/oVirt/ovirt-engine/pull/85
Here is the link on the dashboard:
> Add link to Monitoring Portal on Dashboard

- src/modals/cluster-upgrade/ClusterUpgradeDataProvider.js
- src/utils/random.js
- src/utils/random.test.js
- src/utils/webadmin-search.js
Create a random 10 hex-digit string to use as a correlation id
when starting the cluster upgrade playbook.  The correlation id
will be used by all of the progress events and by the other tasks
run by the ansible role.
Bug-Url: https://bugzilla.redhat.com/show_bug.cgi?id=2040474
Replaces: https://gerrit.ovirt.org/c/ovirt-engine-ui-extensions/+/118294
> cluster upgrade: use correlation id for ansible playbooks

- src/integrations/buttons.js
- src/intl/messages.js
- src/plugin-api.d.ts
move the 'Export' button to kebab menu along with other export VM
options and change button label text to 'Export to Data Domain'.
Bug-Url: https://bugzilla.redhat.com/1979052
> Export VM: move button to kebab menu and rename button label

- packaging/build.sh
In the case of a HEAD commit having multiple tags, the existing
build script would fail to recognize it as a tagged commit and
build as a snapshot build.  The simple fix to add some quotes fixes
this issue.  Now a commit with any number of tags will produce a
release build.
> build: support HEAD with multiple tags

- .github/workflows/build-master.yaml
Replicating the copr build in github actions.  When commits are
pushed to master, or when a label with the release format is pushed
to master, run a build.
> github action: build on push to master or add release label

- src/constants.js
- src/integrations/buttons.js
- src/intl/messages.js
- src/modals/vm-manage-gpu/GpuDataProvider.js
- src/modals/vm-manage-gpu/ManageGpuModal.js
- src/modals/vm-manage-gpu/ManageGpuModalBody.js
- src/modals/vm-manage-gpu/vgpu.css
- src/utils/CompatibilityVersion.js
- src/utils/fetch.js
The backend side of the mdev (vGPUs) has been changed from using custom properties to vm devices + a new driver parameters field has been added to the dialog. In addition to that, the dialog has been moved from host devices tab to vm devices tab.
When there are inconsistencies in the data in the database (e.g. the user inserted the devices using REST API), the following warnings are displayed.
Bug-Url: https://bugzilla.redhat.com/show_bug.cgi?id=1987121
> vm-manage-gpu: Update mdevs

- src/constants.js
- src/integrations/buttons.js
- src/integrations/showStorageConnectionsModal.js
- src/intl/messages.js
- src/modals/storage-connections/StorageConnectionsDataProvider.js
- src/modals/storage-connections/StorageConnectionsModal.js
- src/modals/storage-connections/StorageConnectionsModalBody.js
- src/modals/storage-connections/StorageConnectionsTable.js
- src/modals/storage-connections/connections.css
- src/utils/fetch.js
Storage Connections management dialog is opened by clicking the
Connections button in the Storage Domains table when iSCSI Storage
Domain is selected.
The dialog displays storage connections, attached to the domain, and
also has a switch to show all the iSCSI connections. It allows 5
actions to be performed on the connections:
1. Add new connection
2. Edit connection
3. Remove connection
4. Attach connection to the domain
5. Detach connection from the domain
Which provides UI for the existing storage connections API
Live changes are not supported, thus the domain should be in
maintenance mode to perform actions (4),(5), and also (2),(3) for
attached connections
Bug: https://bugzilla.redhat.com/show_bug.cgi?id=977379
.
> Introduce Storage Connections management dialog

- package.json
- yarn.lock
Update ansi-regex dependency to 5.0.1
Update normalize-url dependency to 4.5.1
Update trim-off-newlines dependency to 1.0.3
Bug-Url: https://bugzilla.redhat.com/1972275
Bug-Url: https://bugzilla.redhat.com/1996701
Bug-Url: https://bugzilla.redhat.com/2008376
> Update ansi-regex, normalize-url and trim-off-newlines dependencies

- src/modals/vm-manage-gpu/GpuDataProvider.js
- src/modals/vm-manage-gpu/ManageGpuModal.js
- src/utils/CompatibilityVersion.js
This is a follow-up patch to address the comments from https://github.com/oVirt/ovirt-engine-ui-extensions/pull/45
GpuDataProvider
- replace lodash/get by ?
- wrap long lines
- create constants for the keys used on the REST API calls (mdevType, driverParams, noDisplay)
- change selectedMDevs from array to object
ManageGpuModal
- rename fields for better readability
> vGPU small code refactorings

- src/modals/vm-manage-gpu/ManageGpuModal.js
- src/modals/vm-manage-gpu/ManageGpuModalBody.js
Currently, if a VM is set with vGPU but its cluster does not contain vGPU hosts any more, it is not possible to view
the configuration or to remove the devices and as a result to run the VM.
This patch allows to review the configuration and to remove the devices in case there are no vGPU hosts in the cluster.
> vGPU: Show widgets even if no vGPU host found

- src/components/modals/PluginApiModal.js
- src/dashboard/UtilizationDialog.js
- src/integrations/showStorageConnectionsModal.js
- src/modals/cluster-upgrade/ClusterUpgradeModal.js
- src/modals/cpu-pinning/CpuPinningModal.js
- src/modals/host-copy-network/HostCopyNetworksModal.js
- src/modals/storage-connections/StorageConnectionsModal.js
- src/modals/vm-export/VmExportModal.js
- src/modals/vm-manage-gpu/ManageGpuModal.js
- src/modals/vm-manage-gpu/ManageGpuModalBody.js
- src/modals/vm-migrate/VmMigrateModal.js
- src/utils/react-modals.js
Originally the `PluginApiModal` component used an unique and auto-generated string for the component's id.  This caused render issues for all modals since the `id` param would be changed each time any other props of the component would change.  The `id` change would then trigger the modal's CSS add/remove `useEffect`.
It was functional but caused lots of strange render issues.  The issue is quite prominent in Chrome.  Firefox doesn't have the same issue as it seems to handle CSS link changes much better.
The fix is to make the `id` static and required for each use.
Additional refactoring was done to keep the code that interacts with the hosting webadmin page all in the same place.  `renderComponent()` is now in charge of where CSS get added to the hosting document.
- remove `showModal()` …
> Fix `renderComponent()` to minimize CSS flashing

- src/modals/cpu-pinning/CpuPinningModalBody.js
When fetching cpu units for a specific host (`cpuunits` endpoint ) returns an empty reply, the following message appears with a trailing zero "`No CPU topology found0`":
This PR fixes it by replacing the zero value (converted to str) with a boolean value.
After this fix:
> Cpu Pinning: fix trailing zero in case of no CPU topology was found

- src/constants.js
- src/services/app-init.js
- zanata/zanata-pull.sh
- zanata/zanata-push.sh
Enable use of community provided translation for Georgian.  After this PR is merged, another PR to import the translation itself should be done.
Related changes:
- ovirt-web-ui: https://github.com/oVirt/ovirt-web-ui/pull/1582
- ovirt-engine: https://github.com/oVirt/ovirt-engine/pull/269
Zanata link: https://zanata.ovirt.org/iteration/view/ovirt-engine-ui-extensions/1.3/languages/ka
> Add support for Georgian language as a community translation

- .github/workflows/build-master.yaml
- .github/workflows/check.yaml
Since we use the ovirt buildcontainer[1] with `ovirt-engine-nodejs-modules`
already installed, there is a gap in time from when we update
nodejs-modules and when it becomes available in the container.  The container
builds at least once a day.
To facilitate our use of nodejs-modules and allow us to use pre-seed
updates as soon as they are available in copr, the github actions are
updated to always `dnf upgrade` the package.  If no upgrades are available,
the operation will take very little time.
[1] - https://github.com/oVirt/buildcontainer
> github actions: always upgrade nodejs-modules

- packaging/build.sh
Using only the date part in RPM snapshots names is not fine enough - when a couple
of builds land in COPR with the same date, the one with the "biggest SHA"
wins, even though it might not actually be the latest build.
> build: Use hours, minutes and seconds in RPM version

- src/modals/cluster-upgrade/data.js
If the upgrade process took more than the `TRACK_FREQUENCY_MS` fetch
interval to generate events, the code would jump back to the beginning
of the events and fetch too many for display.  Make sure not to reset
the `lastEventId` improperly.
> cluster upgrade: fix `trackUpgradeProgress` to always fetch events from the last point

- src/components/patternfly/UtilizationBarChart.js
The Intl.NumberFormat usage for percent value style requires a fraction and not a
percent value.
Check https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/NumberFormat/NumberFormat#decimal_and_percent_formatting
Since the UtilizationBarChart values are calculated in percent already
https://github.com/oVirt/ovirt-engine-ui-extensions/blob/6b2d486846b4835f7737b68fe8dfb224e538ce5e/src/components/patternfly/UtilizationBarChart.js#L18
then need to divide them by 100 to convert to a fraction again.
I went over all other formatPercent method usages to check that we
didn't miss other such occurences and it looks ok.
Bug-Url: https://bugzilla.redhat.com/2108612
> Fix UtilizationBarChart percentage message parameter value

- src/modals/cluster-upgrade/ClusterUpgradeDataProvider.js
- src/modals/cluster-upgrade/ClusterUpgradeModal.js
- src/modals/cluster-upgrade/ClusterUpgradeWizard.js
- src/modals/cluster-upgrade/TrackProgress.js
- src/modals/cluster-upgrade/data.js
Refactor progress tracking, moving it from `TrackProgress` to `ClusterUpgradeDataProvider`.
This way `ClusterUpgradeDataProvider` is the thing in charge of all data access for the modal.
Note: Before #50, modals would be unmounted and recreated with each prop update done in a data provider. After PR #50, prop updates work as expected, and changes are pushed down.  :smile:
> cluster upgrade: refactor progress tracking

- README.adoc
- packaging/build.sh
- packaging/spec.in
Instead of sed swapping in a 0 or 1 for a `%define` variable
in the `spec.in` file for `OFFLINE_BUILD`, add a conditional build.
See [1] for how they work.
With a conditional build, source rpms retain the ability to build with
different options depending on how `rpmbuild` is called.  This allows
an offline (using `ovirt-engine-nodejs-modules`) or online (using
`yarn install`) build from srpm to be selected at build time using
`--with` or `--without` build options.
Since at least copr builds chroots directly from a srpm, conditional
builds can be used to change build options.  With this change, an
"online build" can be enabled simply by configuring the target chroot
setting "without" to include "ovirt_use_nodejs_modules".
Notes:
- An offline build with `ovirt-engine-nodejs-modules` is the …
> build: add conditional build for offline/online builds

- src/modals/vm-export/VmExportDataProvider.js
If a user somehow has null as original_tamplate in a vm values then export to data domain will be blocked by an error. the bug fix will the blocker.
Bug-Url: https://bugzilla.redhat.com/2100194
Signed-off-by: Artiom Divak <adivak@redhat.com>
> Null value blockes user export to daa domain

- .github/workflows/build-master.yaml
- .github/workflows/check.yaml
- Upgrade to currently supported versions of actions used in `build-master.yaml` and `check.yaml`. [1]
- Upgrade set-output command used for node_modules caching [2]
[1]: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/ [2]: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
Signed-off-by: Scott J Dickerson <sdickers@redhat.com>
> github actions: update action versions to current
